import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { supabase, Alert } from '@/lib/supabase';
import { executeResponse, getResponseHistory } from '@/lib/incidentResponse';
import { useAuth } from '@/contexts/AuthContext';
import { Brain, Clock, Shield, Terminal, ArrowLeft, Zap, AlertTriangle, CheckCircle, Loader } from 'lucide-react';

export default function AnalysisPage() {
  const { id } = useParams();
  const { user } = useAuth();
  const [alert, setAlert] = useState<Alert | null>(null);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [aiTyping, setAiTyping] = useState(true);
  const [executingAction, setExecutingAction] = useState<string | null>(null);
  const [responseMessage, setResponseMessage] = useState<string | null>(null);
  const [responseHistory, setResponseHistory] = useState<any[]>([]);

  useEffect(() => {
    async function fetchData() {
      if (id) {
        const { data } = await supabase.from('alerts').select('*').eq('id', id).maybeSingle();
        setAlert(data);
        
        // Load response history
        const history = await getResponseHistory(id);
        setResponseHistory(history);
      }
      const { data: allAlerts } = await supabase.from('alerts').select('*').order('created_at', { ascending: false });
      setAlerts(allAlerts || []);
    }
    fetchData();
    setTimeout(() => setAiTyping(false), 2000);
  }, [id]);

  const handleExecuteResponse = async (action: string, target: string = 'default') => {
    if (!alert || !user?.id) return;

    setExecutingAction(action);
    setResponseMessage(null);

    try {
      const result = await executeResponse(alert.id, action as any, target, user.id);
      setResponseMessage(result.result);

      // Refresh response history
      const history = await getResponseHistory(alert.id);
      setResponseHistory(history);
    } catch (error) {
      setResponseMessage(`Error: ${error}`);
    } finally {
      setExecutingAction(null);
    }
  };

  const selectedAlert = alert || alerts[0];

  const aiResponse = selectedAlert ? `
## Threat Analysis Report

**Classification**: ${selectedAlert.severity.toUpperCase()} Priority Incident
**Confidence Score**: 94.2%

### Executive Summary
${selectedAlert.ai_summary || 'Analyzing threat patterns and correlating with known attack signatures...'}

### Attack Vector Analysis
Based on network traffic patterns and payload inspection, this incident exhibits characteristics consistent with:
- Advanced reconnaissance techniques
- Potential lateral movement indicators  
- Command & Control communication patterns

### Recommended Actions
${selectedAlert.recommended_action || '1. Isolate affected systems\n2. Preserve forensic evidence\n3. Update detection rules'}

### IOCs Identified
\`\`\`
Source IP: ${selectedAlert.source}
Timestamp: ${new Date(selectedAlert.created_at).toISOString()}
Attack Type: ${selectedAlert.title?.split(':')[1]?.trim() || 'Unknown'}
\`\`\`

### MITRE ATT&CK Mapping
- **Tactic**: Initial Access (TA0001)
- **Technique**: Exploit Public-Facing Application (T1190)
- **Sub-technique**: T1190.001

---
*Analysis generated by SOC AI Engine v2.4*
  `.trim() : 'Select an alert to view AI analysis...';

  return (
    <div className="flex gap-md h-full">
      {/* Alert List */}
      <div className="w-72 flex-shrink-0 bg-bg-surface border border-border-subtle rounded-lg overflow-hidden">
        <div className="p-md border-b border-border-subtle">
          <div className="flex items-center gap-sm">
            <Brain size={18} className="text-cyber-primary" />
            <h2 className="text-h2 font-medium text-text-main">AI Analysis</h2>
          </div>
        </div>
        <div className="overflow-y-auto h-[calc(100%-60px)]">
          {alerts.map(a => (
            <Link
              key={a.id}
              to={`/analysis/${a.id}`}
              className={`block p-sm border-b border-border-subtle/50 hover:bg-bg-elevated transition-all ${
                selectedAlert?.id === a.id ? 'bg-cyber-primary/10 border-l-2 border-cyber-primary' : ''
              }`}
            >
              <div className="flex items-center gap-sm mb-xs">
                <span className={`w-2 h-2 rounded-full ${
                  a.severity === 'critical' ? 'bg-status-critical' : 
                  a.severity === 'high' ? 'bg-status-warning' : 'bg-yellow-500'
                }`} />
                <span className="text-xs text-text-muted font-mono">{a.id.slice(0, 8)}</span>
              </div>
              <p className="text-small text-text-main truncate">{a.title}</p>
              <p className="text-xs text-text-muted mt-xs">{new Date(a.created_at).toLocaleString()}</p>
            </Link>
          ))}
        </div>
      </div>

      {/* Analysis Panel */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-md">
        {/* AI Response */}
        <div className="bg-bg-surface border border-border-subtle rounded-lg overflow-hidden">
          <div className="p-md border-b border-border-subtle flex items-center gap-sm">
            <Terminal size={18} className="text-status-success" />
            <span className="text-h2 font-medium text-text-main">AI Assessment</span>
            {aiTyping && (
              <span className="ml-auto flex items-center gap-xs text-small text-cyber-primary">
                <span className="animate-pulse">Analyzing</span>
                <span className="animate-bounce">...</span>
              </span>
            )}
          </div>
          <div className="p-md h-[calc(100%-60px)] overflow-y-auto bg-black/50">
            <pre className="font-mono text-small text-status-success whitespace-pre-wrap leading-relaxed">
              {aiResponse}
            </pre>
          </div>
        </div>

        {/* Threat Details */}
        <div className="space-y-md">
          {selectedAlert && (
            <>
              <div className="bg-bg-surface border border-border-subtle rounded-lg p-md">
                <div className="flex items-center gap-sm mb-md">
                  <AlertTriangle size={18} className={
                    selectedAlert.severity === 'critical' ? 'text-status-critical' : 'text-status-warning'
                  } />
                  <h3 className="text-h2 font-medium text-text-main">Threat Header</h3>
                </div>
                <div className="grid grid-cols-2 gap-md text-small">
                  <div>
                    <span className="text-text-muted">Alert ID</span>
                    <p className="text-text-main font-mono">{selectedAlert.id}</p>
                  </div>
                  <div>
                    <span className="text-text-muted">Source IP</span>
                    <p className="text-cyber-primary font-mono">{selectedAlert.source}</p>
                  </div>
                  <div>
                    <span className="text-text-muted">Severity</span>
                    <p className={
                      selectedAlert.severity === 'critical' ? 'text-status-critical' : 'text-status-warning'
                    }>{selectedAlert.severity.toUpperCase()}</p>
                  </div>
                  <div>
                    <span className="text-text-muted">Detected</span>
                    <p className="text-text-main">{new Date(selectedAlert.created_at).toLocaleString()}</p>
                  </div>
                </div>
              </div>

              <div className="bg-bg-surface border border-border-subtle rounded-lg p-md">
                <div className="flex items-center gap-sm mb-md">
                  <Zap size={18} className="text-cyber-primary" />
                  <h3 className="text-h2 font-medium text-text-main">Automated Response</h3>
                </div>
                <div className="space-y-sm">
                  <button
                    onClick={() => handleExecuteResponse('isolate_host')}
                    disabled={executingAction === 'isolate_host' || selectedAlert?.status === 'mitigated'}
                    className={`w-full border rounded-md py-sm px-md text-small hover:bg-status-critical/20 transition-all text-left flex items-center gap-sm ${
                      executingAction === 'isolate_host'
                        ? 'bg-status-critical/10 border-status-critical/30 text-status-critical opacity-75 cursor-not-allowed'
                        : 'bg-status-critical/10 border-status-critical/30 text-status-critical'
                    }`}
                  >
                    {executingAction === 'isolate_host' && <Loader size={14} className="animate-spin" />}
                    Isolate Affected Host
                  </button>
                  <button
                    onClick={() => handleExecuteResponse('block_ip', selectedAlert?.source)}
                    disabled={executingAction === 'block_ip' || selectedAlert?.status === 'mitigated'}
                    className={`w-full border rounded-md py-sm px-md text-small hover:bg-status-warning/20 transition-all text-left flex items-center gap-sm ${
                      executingAction === 'block_ip'
                        ? 'bg-status-warning/10 border-status-warning/30 text-status-warning opacity-75 cursor-not-allowed'
                        : 'bg-status-warning/10 border-status-warning/30 text-status-warning'
                    }`}
                  >
                    {executingAction === 'block_ip' && <Loader size={14} className="animate-spin" />}
                    Block Source IP
                  </button>
                  <button
                    onClick={() => handleExecuteResponse('update_firewall')}
                    disabled={executingAction === 'update_firewall' || selectedAlert?.status === 'mitigated'}
                    className={`w-full border rounded-md py-sm px-md text-small hover:bg-cyber-primary/20 transition-all text-left flex items-center gap-sm ${
                      executingAction === 'update_firewall'
                        ? 'bg-cyber-primary/10 border-cyber-primary/30 text-cyber-primary opacity-75 cursor-not-allowed'
                        : 'bg-cyber-primary/10 border-cyber-primary/30 text-cyber-primary'
                    }`}
                  >
                    {executingAction === 'update_firewall' && <Loader size={14} className="animate-spin" />}
                    Update Firewall Rules
                  </button>
                </div>

                {responseMessage && (
                  <div className={`mt-md p-sm rounded-md border text-small ${
                    responseMessage.includes('success') || responseMessage.includes('successfully')
                      ? 'bg-status-success/10 border-status-success/30 text-status-success'
                      : 'bg-status-critical/10 border-status-critical/30 text-status-critical'
                  }`}>
                    {responseMessage.includes('success') || responseMessage.includes('successfully') ? (
                      <CheckCircle size={14} className="inline mr-sm" />
                    ) : (
                      <AlertTriangle size={14} className="inline mr-sm" />
                    )}
                    {responseMessage}
                  </div>
                )}

                {responseHistory.length > 0 && (
                  <div className="mt-md pt-md border-t border-border-subtle">
                    <h4 className="text-small text-text-muted mb-sm">Response History</h4>
                    <div className="space-y-xs max-h-48 overflow-y-auto">
                      {responseHistory.map((resp: any) => (
                        <div
                          key={resp.id}
                          className="text-xs bg-bg-elevated p-xs rounded flex items-center justify-between"
                        >
                          <span className="text-text-main">{resp.action}: {resp.target}</span>
                          <span
                            className={`px-xs rounded ${
                              resp.status === 'success'
                                ? 'bg-status-success/20 text-status-success'
                                : 'bg-status-critical/20 text-status-critical'
                            }`}
                          >
                            {resp.status}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              <div className="bg-bg-surface border border-border-subtle rounded-lg p-md">
                <div className="flex items-center gap-sm mb-md">
                  <Shield size={18} className="text-text-muted" />
                  <h3 className="text-h2 font-medium text-text-main">Payload Sample</h3>
                </div>
                <div className="bg-black rounded-md p-sm font-mono text-small text-status-critical overflow-x-auto">
                  <code>{`GET /api/users?id=1' OR '1'='1'--
Host: internal-api.company.local
User-Agent: Mozilla/5.0 (compatible; sqlmap/1.6)
X-Forwarded-For: ${selectedAlert.source}`}</code>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
